/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * <p>
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 * @nolint
 */

package com.tangem.RNTangemSdk;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

import org.jetbrains.annotations.Nullable;

import javax.annotation.Nonnull;

public abstract class NativeTangemSdkModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
    public static final String NAME = "RNTangemSdk";

    public NativeTangemSdkModuleSpec(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public @Nonnull String getName() {
        return NAME;
    }

    @ReactMethod
    @DoNotStrip
    public abstract void startSession(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void stopSession(Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void scanCard(@Nullable ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void createWallet(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void purgeWallet(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void sign(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void setAccessCode(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void setPasscode(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void resetUserCodes(ReadableMap options, Promise promise);

    @ReactMethod
    @DoNotStrip
    public abstract void getNFCStatus(Promise promise);
}
